FROM debian

RUN apt-get update && apt-get install -y apache2 && apt-get clean

ENV APACHE_LOCK_DIR="/var/lock"
ENV APACHE_PID_FILE="/var/run/apache2.pid"
ENV APACHE_RUN_USER="www-data"
ENV APACHE_RUN_GROUP="www-data"
ENV APACHE_LOG_DIR="/var/log/apache2"

COPY index.html /var/www/html/
ADD index.html /var/www/html/

USER root

WORKDIR /var/www/html/

LABEL description="webserver"
LABEL version="1.0.0"

VOLUME /var/www/html

EXPOSE 80

ENTRYPOINT [ "/usr/sbin/apachectl" ]
CMD [ "-D", "FOREGROUND" ]

# docker image build -t apache:1.0.0 -f 02-dockerfile .
# docker image build -t apache:1.0.1 -f 02-dockerfile . --no-cache
# docker run -d -p 8080:80 apache:1.0.1